### ISSUE TITLE
Failed to install GitLab helm chart

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/helm-charts#155]
When I deploy GitLab app in KubeSphere Apps, KubeSphere complains the following error:

```bash
Error: 

error while running post render on files: error while running command 
/tmp/helm-operator/gitlab-project_gitlab-p7vtz0_8qjk9jm2924x5m/helm-post-render.sh.

error output: Error: map[string]interface {}(nil): yaml: unmarshal errors: line 19:
    mapping key "enable-vts-status" already defined at line 17 : exit status 1
```

That's because resource files rendered by helm contain multi key `enable-vts-status`.

I found that there are some related occurrences:

https://github.com/kubesphere/helm-charts/blob/7c402af51cd9320367a1544c14b5326dea3c4503/src/main/gitlab/values.yaml#L587

https://github.com/kubesphere/helm-charts/blob/7c402af51cd9320367a1544c14b5326dea3c4503/src/main/gitlab/values.yaml#L607

https://github.com/kubesphere/helm-charts/blob/7c402af51cd9320367a1544c14b5326dea3c4503/src/main/gitlab/charts/nginx/templates/controller-configmap.yaml#L11

https://github.com/kubesphere/helm-charts/blob/7c402af51cd9320367a1544c14b5326dea3c4503/src/main/gitlab/charts/nginx/templates/controller-configmap.yaml#L16

# Suggestion

You can remove the dedicated `enable-vts-status` config in [controller-configmap.yaml](https://github.com/kubesphere/helm-charts/blob/bcce25fc318108f2187f0a4e1e3efb3779a4224f/src/main/gitlab/charts/nginx/templates/controller-configmap.yaml) to solve this problem:

https://github.com/kubesphere/helm-charts/blob/7c402af51cd9320367a1544c14b5326dea3c4503/src/main/gitlab/charts/nginx/templates/controller-configmap.yaml#L11

/kind bug
/good-first-issue

**Comment by xyz-li** [comment]
https://github.com/kubesphere/kubesphere/issues/3933

**Comment by JohnNiang** [comment]
I'm going to close this issue due to duplicated with <https://github.com/kubesphere/kubesphere/issues/3933>.

/close
