### ISSUE TITLE
VPA for csi-qingcloud

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/helm-charts#184]
Current csi-qingcloud chart has resource request/limits for every container and it works for most small-size clusters (< 20 nodes). Now csi-qingcloud is widely used in public qingcloud and private clouds. Sometimes, user complains the csi-qingcloud is throttled or OOM killed due to lacks resources for some containers and we then tell them to scale up based on their report.

VPA(Vertical Pod Autoscaler) is a nice feature that we may use to automatically tune the resource request/limits based on some metrics. Please investigate if it's possible and what need to do.

refer:
- https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler)

**Comment by f10atin9** [comment]
#188 fixed.
