### ISSUE TITLE
Invalid curvefs image url in helm chart

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/helm-charts#339]
We keep to receiving below report from artifactry.io, pls check if related URL is still valid? otherwise, it will be treated as invalid helm chart and take offline action from KubeSphere app store, thanks. @h0hmj 

`error scanning image harbor.cloud.netease.com/curve/curvefs:csi-v1.0.0: error running trivy on image harbor.cloud.netease.com/curve/curvefs:csi-v1.0.0: * GET https://harbor.cloud.netease.com/v2/: unexpected status code 403 Forbidden:`

**Comment by h0hmj** [comment]
sorry for the delay. 
you are right. it's invalid now and need to be updated.

@caoxianfei1 will help update the image url

**Comment by caoxianfei1** [comment]
The image has upload to quay `quay.io/opencurve/curve/curvefs:csi-v1.0.0`, and i will open a pr to fix it.
